# Generated by Django 5.0.2 on 2024-02-18 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('acquisition_method', models.CharField(blank=True, max_length=100, verbose_name='获取方式')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='录入时间')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否成单')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='归属')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
    ]
