# Generated by Django 5.0.2 on 2024-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='案件描述'),
        ),
    ]
