# Generated by Django 5.0.2 on 2024-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_delete_resource_customer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=100, unique=True, verbose_name='联系方式'),
        ),
    ]
